version: '3.1'

services:

  blogclient:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'blogclient'
    ports:
      - 8080:80
    volumes:
      - ./client:/var/www/html
