version: '3.8'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: app
    restart: always
    environment:
      UID: 1000
      GID: 1000
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: secret
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html

  database:
    container_name: mysql
    platform: linux/x86_64
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
